<?php
// Database connection details
$servername = "localhost";
$username   = "u964291147_aeroedgemedia";
$password   = "Aeroedge@2025";
$dbname     = "u964291147_aeroedgemedia";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

if ($_SERVER["REQUEST_METHOD"] === "POST") {

    // 1️⃣ Sanitize & validate email
    $email = filter_var(trim($_POST['newsletter-email'] ?? ''), FILTER_SANITIZE_EMAIL);

    if (empty($email)) {
        exit("Email is required!");
    }
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        exit("Invalid email format!");
    }

    // 2️⃣ Check if already subscribed
    $check = $conn->prepare("SELECT * FROM newsletter_subscribers WHERE email = ?");
    $check->bind_param("s", $email);
    $check->execute();
    $result = $check->get_result();

    if ($result->num_rows > 0) {
        exit("⚠️ This email is already subscribed.");
    }

    // 3️⃣ Save to database
    $stmt = $conn->prepare("INSERT INTO newsletter_subscribers (email) VALUES (?)");
    $stmt->bind_param("s", $email);

    if ($stmt->execute()) {

        // 4️⃣ Send email notification to admin
        $to_admin   = "info@aeroedgemedia.com";
        $subject_admin  = "📩 New Newsletter Subscription";
        $message_admin  = "
            <html>
            <body style='font-family: Arial, sans-serif; color: #333;'>
                <h2>New Newsletter Subscription</h2>
                <p><strong>Email:</strong> {$email}</p>
                <p>Subscribed via website form.</p>
                <hr>
                <p style='font-size: 12px; color: #777;'>This message was automatically generated by your website.</p>
            </body>
            </html>
        ";

        $headers_admin  = "MIME-Version: 1.0\r\n";
        $headers_admin .= "Content-type: text/html; charset=UTF-8\r\n";
        $headers_admin .= "From: Aero Edge Media <no-reply@aeroedgemedia.com>\r\n";
        $headers_admin .= "Reply-To: {$email}\r\n";

        mail($to_admin, $subject_admin, $message_admin, $headers_admin);

        // 5️⃣ Send thank-you email to subscriber
        $to_user   = $email;
        $subject_user  = "🎉 Thank You for Subscribing – Aero Edge Media";
        $message_user  = "
            <html>
            <body style='font-family: Arial, sans-serif; color: #333;'>
                <h2>Welcome to Aero Edge Media!</h2>
                <p>Hi there 👋,</p>
                <p>Thank you for subscribing to our newsletter. You’ll now receive the latest updates, marketing insights, and digital growth tips straight to your inbox.</p>
                <p>We’re excited to have you on board!</p>
                <br>
                <p>Best Regards,<br><strong>The Aero Edge Media Team</strong></p>
                <hr>
                <p style='font-size: 12px; color: #777;'>You received this email because you subscribed on our website.</p>
            </body>
            </html>
        ";

        $headers_user  = "MIME-Version: 1.0\r\n";
        $headers_user .= "Content-type: text/html; charset=UTF-8\r\n";
        $headers_user .= "From: Aero Edge Media <no-reply@aeroedgemedia.com>\r\n";

        mail($to_user, $subject_user, $message_user, $headers_user);

        echo "✅ Thank you for subscribing!";
    } else {
        echo "⚠️ Something went wrong while saving your email.";
    }

    $stmt->close();
    $check->close();
}

$conn->close();
?>
